import os
# configfile: "../../configs/config.yaml"
# configfile: "../../configs/config_test.yaml"
configfile: "./build/config.yaml"


rule test:
	params:
		p=1
	output:
		"b"
	shell:
		"echo {params.p} {output} "+config['datapath']+" > b"

rule test_r:
	params:
		p=1
	output:
		opimg=config['homedir']+config['oproot']+'/tmp.png'
	conda:
		"../envs/r_env.yml"
	script:
		"../src/R/test.R"

rule injest_imgs:
	input:
		nissls=config['homedir']+config['datapath']+'/nissls'+'.zip',
		stags=config['homedir']+config['datapath']+'/stags'+'.zip'
	output:
		dataset_dir=directory(config['homedir']+config['oproot']+'/'+config['dataname']+'/raw'),
		# stags_op=directory(config['homedir']+config['oproot']+'/'+config['dataname'])
	shell:
		"unzip {input.nissls} -d {output.dataset_dir} ; unzip {input.stags} -d {output.dataset_dir}"

# rule format_imgs using python script after reading from raw ims directory
rule format_imgs:
	input:
		dataset_dir=rules.injest_imgs.output.dataset_dir
	output:
		dataset_dir=directory(config['homedir']+config['oproot']+'/'+config['dataname']+'/formatted')
	script:
		"../src/workflow/format_imgs.py" # relative to Snakefile (Snakefile link in this case)

fnames, = glob_wildcards(config['homedir']+config['oproot']+'/'+config['dataname']+'/raw/nissls/{fname,[^/]+}.tif')

print (fnames)
print(config['homedir']+config['oproot']+'/'+config['dataname']+'/nissls')

rule all:
	input:
		olayplot=expand(config['homedir']+config['oproot']+'/'+config['dataname']+'/plots/{fname}/overlay_{fname}.png',fname=fnames)

rule prep_rigid_driver:
	input:
		mrml=expand(config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/{fname}.mrml', fname=fnames),
		from_fids=expand(config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/F.mrk.json', fname=fnames),
		to_fids=expand(config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/T.mrk.json', fname=fnames),
		tfm1=expand(config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/Tfm1.txt', fname=fnames)

rule prep_warp_driver:
	input:
		nissl=expand(config['homedir']+config['oproot']+'/'+config['dataname']+'/warps/{fname}/{fname}.tif', fname=fnames),
		stag=expand(config['homedir']+config['oproot']+'/'+config['dataname']+'/warps/{fname}/stag_{fname}.tif', fname=fnames),
		mrml=expand(config['homedir']+config['oproot']+'/'+config['dataname']+'/warps/{fname}/{fname}.mrml', fname=fnames),
		from_fids=expand(config['homedir']+config['oproot']+'/'+config['dataname']+'/warps/{fname}/F.fcsv', fname=fnames),
		to_fids=expand(config['homedir']+config['oproot']+'/'+config['dataname']+'/warps/{fname}/T.fcsv', fname=fnames),
		tfm1ed_pts=expand(config['homedir']+config['oproot']+'/'+config['dataname']+'/warps/{fname}/tfm1ed_pts.txt', fname=fnames),

rule get_tifs:
	input:
		nissls=config['homedir']+config['oproot']+'/'+config['dataname']+'/formatted/nissls/{fname}.tif',
		stags=config['homedir']+config['oproot']+'/'+config['dataname']+'/formatted/stags/{fname}.tif',
	output:
		nissls=config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/{fname}.tif',
		stags=config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/stag_{fname}.tif',
	shell:
		'cp {input.nissls} {output.nissls} && cp {input.stags} {output.stags}'

# rule to copy and materialize slicer templates via python script
rule prep_rigid:
	input:
		nissls=config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/{fname}.tif',
		stags=config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/stag_{fname}.tif',
		template='templates/rigid.mrml'
	output:
		mrml=config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/{fname}.mrml',
		from_fids=config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/F.mrk.json',
		to_fids=config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/T.mrk.json',
		tfm1=config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/Tfm1.txt',

	script:
		"../src/workflow/prep_rigid.py"


# rule to get crop of nissl subregion and copy to warps folder
rule prep_warp:
	input:
		tfm1=rules.prep_rigid.output.tfm1,
		nissl=config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/{fname}.tif',
		stag=config['homedir']+config['oproot']+'/'+config['dataname']+'/rigid/{fname}/stag_{fname}.tif',
		data=config['homedir']+config['oproot']+'/'+config['dataname']+'/raw/stags/{fname}.csv',

	output:
		nissl=config['homedir']+config['oproot']+'/'+config['dataname']+'/warps/{fname}/{fname}.tif',
		stag=config['homedir']+config['oproot']+'/'+config['dataname']+'/warps/{fname}/stag_{fname}.tif',
		mrml=config['homedir']+config['oproot']+'/'+config['dataname']+'/warps/{fname}/{fname}.mrml',
		from_fids=config['homedir']+config['oproot']+'/'+config['dataname']+'/warps/{fname}/F.fcsv',
		to_fids=config['homedir']+config['oproot']+'/'+config['dataname']+'/warps/{fname}/T.fcsv',
		tfm1ed_pts=config['homedir']+config['oproot']+'/'+config['dataname']+'/warps/{fname}/tfm1ed_pts.txt',

	conda:
		'../envs/'+config['envname']+'.yml'

	script:
		"../src/workflow/prep_warp.py"

# rule to create overlay plot from registered stag coords
rule render_plots:
	input:
		nissl=rules.prep_warp.output.nissl,
		from_fids=rules.prep_warp.output.from_fids, # only to indicate prep_warp ran
		to_fids=rules.prep_warp.output.to_fids, # only to indicate prep_warp ran
		tfm1ed_pts=rules.prep_warp.output.tfm1ed_pts,
		template='templates/warp/warp.mrml',
		data=rules.prep_warp.input.data,
	output:
		olayplot=config['homedir']+config['oproot']+'/'+config['dataname']+'/plots/{fname}/overlay_{fname}.png',

	conda:
		'../envs/'+config['envname']+'.yml'
	script:
		"../src/workflow/render_plots.py"

